// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://envgbwdpzudlbqvecksg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudmdid2RwenVkbGJxdmVja3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODY1NTYsImV4cCI6MjA2NTc2MjU1Nn0.YwooLNsm41gkhNWaaostkAHJqA6wUZN5hn-qq-fRzYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);